# Fucking Open Source fucking 1

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# system
system:
  use-multipoint: false
  env: 'develop'  # Change to "develop" to skip authentication for development mode
  addr: 8080
  db-type: "mysql"

# mysql connect configuration
mysql:
  username: root
  password: '123456'
  path: '127.0.0.1:3306'
  db-name: ''
  config: ''
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: true

# logger configuration
log:
  prefix: 'xxx'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'

# oss configuration
qiniu:
  access-key: ''
  secret-key: ''

# jwt configuration
jwt:
  signing-key: 'xxxx'

# redis configuration
redis:
  addr: '127.0.0.1:6379'
  passwprd: ''
  db: 0

